### ISSUE TITLE
ModuleNotFoundError: No module named 'dtcli'

### ISSUE THREAD

**Issue by kozross** [kz26/dottorrent-cli#1]
This is for an install from ``pip``. When I try to run it, I get this error:

    Traceback (most recent call last):
      File "/usr/bin/dottorrent", line 7, in <module>
        from dtcli.cli import main
    ModuleNotFoundError: No module named 'dtcli'

**Comment by kz26** [comment]
Thanks for the bug report. This has been fixed in version 1.10.1 which was just released.
