### ISSUE TITLE
Invalid torrent output paths don't fail until after hashing

### ISSUE THREAD

**Issue by ghost** [kz26/dottorrent-cli#6]
If you specify a torrent output path that can't be written (in my case it was a directory that didn't exist), dottorrent-cli will first hash the torrent data, then attempt to write the torrent file and fail. This is somewhat frustrating since the data now needs to be hashed all over again.

Perhaps it would be better to open the torrent file for writing before the hashing stage to ensure the target file path is in fact writable?

**Comment by kz26** [comment]
Hi, thanks for the report. I'll look into this.

**Comment by kz26** [comment]
Fixed in 1.10.3.
